---
title: "FY12-23YTD ICE ERO arrests descriptive analysis"
author: "UWCHR"
date: "2023-03-27"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

# ICE ERO arrests: Data overview

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, include=TRUE}

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, sf, tigris, ggrepel, ggmap, tidygeocoder)

arr <- read_delim(here('us-fy12-23', 'analyze', 'input', 'arrests.csv.gz'), delim='|',
                  col_types = cols(aor = col_factor(),
                                  arrest_date = col_date(format="%m/%d/%Y"),
                                  departed_date = col_date(format="%m/%d/%Y"),
                                  apprehension_landmark = col_factor(),
                                  arrest_method = col_factor(),
                                  operation = col_factor(),
                                  processing_disposition = col_factor(),
                                  citizenship_country = col_factor(),
                                  gender = col_factor(),
                                  case_closed_date = col_date(format="%m/%d/%Y"),
                                  id = col_integer(),
                                  hashid = col_character()
                                  )) 

redacted <- c('removal_threat_level', 'apprehension_threat_level', 'alien_file_number')

arr <- arr %>% 
  dplyr::select(-all_of(redacted))

arr <- arr %>% 
  mutate(arrest_date = as_date(arrest_date, format="%m/%d/%Y"),
         year = year(arrest_date),
         month = month(arrest_date, label=TRUE, abbr=TRUE),
         year_mth = zoo::as.yearmon(arrest_date),
         fy = as.factor(substr(quarter(arrest_date, fiscal_start=10, type="year.quarter"), 1,4)),
         citizenship_country = as.factor(toupper(citizenship_country)))

# skimr::skim(arr)

county_aor <- read_delim(here('share', 'hand', 'county_aor.csv'), delim = ',')

demog <- read_delim(here('us-fy12-23', 'analyze', 'input', 'aor_demog_indicators.csv.gz'), delim='|') %>%
  arrange(aor, year)

pc_scale = 100000

ggkey = Sys.getenv("GOOGLEGEOCODE_API_KEY")
print(ggkey)
register_google(key = ggkey)

aor_field_office <- read_delim(here('share', 'hand', 'aor_ero_field_office.csv'), delim = ',')

# aor_field_office_lat_lon <- geo(aor_field_office$field_office_addr, method="google")
# 
# aor_field_office <- aor_field_office %>% 
#   mutate(field_office_addr = str_squish(field_office_addr)) %>% 
#   left_join(aor_field_office_lat_lon, by=c('field_office_addr' = 'address'))
# 
# write_delim(aor_field_office, here('share', 'hand', 'aor_ero_field_office.csv'), delim = ',')

aor_field_office_sf <- aor_field_office %>%
  st_as_sf(coords = c("long", "lat"), crs=4326)

```

# Total arrests by FY

```{r fy_total, echo=FALSE, message=FALSE, include=TRUE}

p1 <- arr %>% 
  filter(arrest_date <= "2022-09-30") %>% 
  group_by(fy) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.factor(fy), y=n)) +
  geom_col() +
  labs(title = "Total ICE arrests per FY")

p1

```


# Basic AOR map

```{r annual, echo=FALSE, message=FALSE, include=TRUE}
  
states <- unique(county_aor$geoid_state)

all_counties <- counties(state=states) %>% 
  shift_geometry() 

# We can easily combine county-level geometries into an AOR shape!

aor_geom <- left_join(all_counties, county_aor, by=c('GEOID' = "geoid")) %>% 
  group_by(aor) %>% 
  summarize(geometry = sf::st_union(geometry))

dat <- aor_geom %>% 
  left_join(demog, by='aor')

dat %>%
  ggplot(aes(fill=aor)) +
  geom_sf(color='black') +
  geom_sf(data = aor_field_office_sf, aes(geometry = geometry), show.legend = FALSE) +
  ggrepel::geom_label_repel(
    data = aor_field_office_sf,
    aes(label = aor, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0,
    force=2,
    show.legend = FALSE
  ) +
  theme_void() +
  labs(title = "ICE AORs")

```

```{r arrests_per_capita}

arr_per_aor <- arr %>% 
  filter(!is.na(aor),
         aor != "HQ",
        arrest_date <= "2022-09-30") %>% 
  group_by(fy, aor) %>% 
  summarize(n = n()) %>% 
  mutate(fy = as.numeric(as.character(fy)))

dat <- full_join(demog, arr_per_aor, by=c('aor' = 'aor', 'year' = 'fy')) %>% 
  group_by(aor) %>% 
  fill(contains('pop')) %>% 
  left_join(aor_geom, by='aor') 
  

dat %>%
  filter(year == 2019) %>%
  ggplot(aes(geometry=geometry, fill=n)) +
  geom_sf() +
  theme_void() +
  labs(title = "Total ICE arrests, 2019")

dat %>%
  filter(year == 2019) %>% 
  mutate(arrests_pc = n / total_pop * pc_scale) %>% 
  ggplot(aes(geometry=geometry, fill=arrests_pc)) +
  geom_sf() +
  theme_void() +
  labs(title = "ICE arrests per 100,000 pop., 2019")

dat %>%
  filter(year == 2019) %>% 
  mutate(arrests_per_undocu = n / undocu_pop * pc_scale) %>% 
  ggplot(aes(geometry=geometry, fill=arrests_per_undocu)) +
  geom_sf() +
  theme_void() +
  labs(title = "ICE arrests per 100,000 potentially undocumented pop., 2019")  
  
```

# Percent change

Percent change in arrests per FY nationally and by AOR. Note comparison between groups may be misleading because smaller population AORs will be more volatile.

```{r arrests_pct_chg, message=FALSE, warning=FALSE}

biden_start <- "2021-01-20"
trump_start <- "2017-01-20"
obama_2_start <- "2013-01-20"
obama_1_start <- "2009-01-20"

arr <- arr %>% 
  mutate(admin = case_when(arrest_date >= biden_start ~ "biden",
                           arrest_date >= trump_start & arrest_date < biden_start ~ "trump",
                           arrest_date >= obama_2_start & arrest_date < trump_start ~ "obama",
                           arrest_date >= obama_1_start & arrest_date < obama_2_start ~ "obama"),
         admin = factor(admin, levels=c('obama', 'trump', 'biden')))

admin_pct_chg <- arr %>%
  filter(arrest_date >= obama_2_start) %>% 
  group_by(admin, aor, arrest_method) %>%
  summarize(n = n()) %>% 
  group_by(aor, arrest_method) %>% 
  mutate(pct_change = (n/lag(n) - 1)) %>% 
  filter(arrest_method == "CAP Local Incarceration")



natl_pct_chg <- arr %>%
  filter(arrest_date <= "2022-09-30") %>% 
  group_by(fy) %>%
  summarize(n = n()) %>% 
  mutate(pct_change = (n/lag(n) - 1))

p1 <- natl_pct_chg %>% 
  ggplot(aes(x = fy, y = pct_change)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title="FY % change in total ICE arrests")

p1

aor_pct_chg <- arr %>%
  filter(arrest_date <= "2022-09-30",
         !is.na(aor)) %>% 
  group_by(fy, aor) %>%
  summarize(n = n()) %>% 
  group_by(aor) %>% 
  arrange(fy, .by_group=TRUE) %>% 
  mutate(pct_change = (n/lag(n) - 1))

p2 <- aor_pct_chg %>% 
  ggplot(aes(x = fy, y = pct_change)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  scale_x_discrete(breaks=seq(2012, 2022, 2)) +
  facet_wrap(~aor)  +
  labs(title="FY % change in total ICE arrests per AOR") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

p2

# Could try superimposing line chart of total arrests as above

```

