---
title: "FY12-23YTD ICE ERO descriptive analysis"
author: "UWCHR"
date: "2023-03-27"
output:
  pdf_document: default
  html_document: default
---
 

```{r setup, echo=FALSE, message=FALSE, include=TRUE}

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight)

pd_dict <- read_delim(here('share', 'hand', 'processing_disp.csv'), delim='|')

rem <- read_delim(here('us-fy12-23', 'analyze', 'input', 'removals.csv.gz'), delim='|',
                  col_types = cols(aor = col_character(),
                                   arrest_date = col_date(format="%m/%d/%Y"),
                                  departed_date = col_date(format="%m/%d/%Y"),
                                  case_close_date = col_date(format="%m/%d/%Y"),
                                  removal_date = col_date(format="%m/%d/%Y"),
                                  apprehension_method_code = col_character(),
                                  processing_disposition_code = col_factor(),
                                  citizenship_country = col_factor(),
                                  gender = col_factor(),
                                  final_charge_section = col_factor(),
                                  id = col_integer(),
                                  hashid = col_character()
                                  )) 

glimpse(rem)

redacted <- c('removal_threat_level', 'alien_file_number')

rem <- rem %>% 
  dplyr::select(-redacted)

rem <- rem %>% 
  mutate(year = year(departed_date),
         month = month(departed_date, label=TRUE, abbr=TRUE),
         year_mth = zoo::as.yearmon(departed_date),
         processing_disp = toupper(coalesce(processing_disposition_code, processing_disposition)),
         date = coalesce(departed_date, removal_date),
         fy = as.numeric(substr(quarter(date, fiscal_start=10, type="year.quarter"), 1,4)))

rem <- left_join(rem, pd_dict, by=c('processing_disp' = 'processing_disposition_raw'))

```

```{r gender, echo=FALSE, message=FALSE, include=TRUE}

rem %>%
  mutate(gender = tolower(gender)) %>% 
  group_by(gender) %>% 
  summarize(n = n())

```


```{r cit, echo=FALSE, message=FALSE, include=TRUE}

rem %>%
  mutate(citizenship_country = tolower(citizenship_country)) %>% 
  group_by(citizenship_country) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

```

## Total removals

```{r fy_total, echo=FALSE, message=FALSE, include=TRUE}

p1 <- rem %>% 
  filter(date >= "2011-10-01",
         date <= "2022-09-30") %>% 
  group_by(fy) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.factor(fy), y=n)) +
  geom_col() +
  labs(title = "Total removals per FY")

p1

```

```{r annual, echo=FALSE, message=FALSE, include=TRUE}

p1 <- rem %>% 
  filter(date >= "2011-10-01",
         date <= "2022-09-30") %>% 
  group_by(fy, aor) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.factor(fy), y=n, color=aor, group=aor)) +
  geom_line() +
  labs(title = "Total removals per FY by AOR")

ggplotly(p1)

```

Below is a chart of total ICE arrests per FY, highlighting the Seattle AOR ("SEA"):

```{r annual_sea}


p2 <- rem %>% 
  filter(date >= "2011-10-01",
         date <= "2022-09-30") %>% 
  group_by(fy, aor) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.factor(fy), y=n, color=aor, group=aor)) +
  geom_line() +
  gghighlight(aor == "SEA") +
  labs(title = "Total removals per FY",
       subtitle = "Seattle AOR highlighted")

p2

```

```{r removals_pct_chg}

natl_pct_chg <- rem %>%
  filter(date >= "2011-10-01",
         date <= "2022-09-30") %>% 
  group_by(fy) %>%
  summarize(n = n()) %>% 
  mutate(pct_change = (n/lag(n) - 1))

p1 <- natl_pct_chg %>% 
  ggplot(aes(x = fy, y = pct_change)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  labs(title="FY % change in total removals")

p1

aor_pct_chg <- rem %>%
  filter(date >= "2011-10-01",
         date <= "2022-09-30",
         aor != "HQ",
         !is.na(aor)) %>% 
  group_by(fy, aor) %>%
  summarize(n = n()) %>% 
  group_by(aor) %>% 
  arrange(fy, .by_group=TRUE) %>% 
  mutate(pct_change = (n/lag(n) - 1))

p2 <- aor_pct_chg %>% 
  ggplot(aes(x = fy, y = pct_change)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  scale_x_discrete(breaks=seq(2012, 2022, 2)) +
  facet_wrap(~aor)  +
  labs(title="FY % change in total removals per AOR") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

p2

# Could try superimposing line chart of total arrests as above

```

## Removals by processing disposition

```{r disp, echo=FALSE, message=FALSE, include=TRUE}

disps <- rem %>% 
  filter(date >= "2012-10-01",
         date <= "2022-09-30",
         ) %>% 
  count(processing_disposition_clean) %>% 
  arrange(desc(n))

top_disp <- disps %>% 
  filter(n > 50000)

rem <- rem %>% 
  mutate(disp_short = case_when(processing_disposition_clean %in% unlist(top_disp$processing_disposition_clean) ~ as.character(processing_disposition_clean), 
                                         TRUE ~ "ALL OTHERS"))


```

```{r rem_disp_fy}

p1 <- rem %>% 
  filter(date >= "2012-10-01",
         date <= "2022-09-30",
         ) %>% 
  group_by(fy, disp_short) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.factor(fy), y=n, fill=disp_short)) +
  geom_col() +
  labs(title = "Total removals per FY by processing disposition")

ggplotly(p1)

```

```{r expedited_removal, echo=FALSE, message=FALSE, include=TRUE}

er <- c('er', 'ex')

rem <- rem %>% 
  mutate(processing_disp = tolower(processing_disp),
         ex_rem = case_when(processing_disp %in% er ~ 'expedited removal',
                            str_detect(processing_disp, 'expedited removal') ~ 'expedited removal',
                            is.na(processing_disp) ~ 'all others',
                            TRUE ~ 'all others'))

p1 <- rem %>% 
  group_by(year, ex_rem) %>%
  ggplot(aes(x = year, fill=ex_rem)) +
  geom_bar(stat='count')

p1

p1 <- rem %>% 
  group_by(year, aor, ex_rem) %>%
  ggplot(aes(x = year, fill=ex_rem)) +
  geom_bar(stat='count') +
  facet_wrap(~aor, scales="free_y")

p1

```

```{r date_compare, echo=FALSE, message=FALSE, include=TRUE}

rem$dep_diff_rem <- difftime(rem$departed_date, rem$removal_date, units='days')

median(rem$dep_diff_rem, na.rm=TRUE)
mean(rem$dep_diff_rem, na.rm=TRUE)
max(rem$dep_diff_rem, na.rm=TRUE)
min(rem$dep_diff_rem, na.rm=TRUE)

h1 <- hist(as.numeric(rem$dep_diff_rem))

p1 <- plot(as.numeric(rem$dep_diff_rem))

```

```{r plot dates}

p1 <- plot(rem$id, rem$departed_date)

p2 <- plot(rem$id, rem$removal_date)

p3 <- plot(rem$removal_date, rem$departed_date)
```

