---
title: "FY12-23YTD ICE ERO descriptive analysis"
author: "UWCHR"
date: "2023-03-27"
output:
  pdf_document: default
  html_document: default
---
 

```{r setup, echo=FALSE, message=FALSE, include=TRUE}

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight)

arr <- read_delim(here('us-fy12-23', 'analyze', 'input', 'arrests.csv.gz'), delim='|',
                  col_types = cols(aor = col_character(),
                                  arrest_date = col_date(format="%m/%d/%Y"),
                                  departed_date = col_date(format="%m/%d/%Y"),
                                  apprehension_landmark = col_character(),
                                  operation = col_factor(),
                                  processing_disposition = col_factor(),
                                  citizenship_country = col_factor(),
                                  gender = col_factor(),
                                  case_closed_date = col_date(format="%m/%d/%Y"),
                                  id = col_integer(),
                                  hashid = col_character()
                                  )) 

glimpse(arr)

redacted <- c('removal_threat_level', 'apprehension_threat_level', 'alien_file_number')

arr <- arr %>% 
  dplyr::select(-redacted)

arr <- arr %>% 
  mutate(arrest_date = as_date(arrest_date, format="%m/%d/%Y"),
         year = year(arrest_date),
         month = month(arrest_date, label=TRUE, abbr=TRUE),
         year_mth = zoo::as.yearmon(arrest_date),
         fy = substr(quarter(arrest_date, fiscal_start=10, type="year.quarter"), 1,4))

arr_methods_unique <- unique(tolower(arr$arrest_method))
arr_disp_unique <- unique(tolower(arr$processing_disposition))


write_lines(arr_methods_unique, '../output/arr_methods.txt')
write_lines(arr_disp_unique, '../output/arr_disp.txt')

```

```{r gender, echo=FALSE, message=FALSE, include=TRUE}

arr %>%
  mutate(gender = tolower(gender)) %>% 
  group_by(gender) %>% 
  summarize(n = n())

```


```{r cit, echo=FALSE, message=FALSE, include=TRUE}

arr %>%
  mutate(citizenship_country = tolower(citizenship_country)) %>% 
  group_by(citizenship_country) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

```

Note "Not amenable to removal" largest category; check % of this and other categories like "foreign born usc", "not in custody" (also indicates no arrest?)

```{r disp, echo=FALSE, message=FALSE, include=TRUE}

arr %>%
  mutate(processing_disposition = tolower(processing_disposition)) %>% 
  group_by(processing_disposition) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

arr <- arr %>%
  mutate(processing_disposition = tolower(processing_disposition),
         disp_exp = case_when(str_detect(processing_disposition, 'expedited removal') ~ 'expedited removal',
                             TRUE ~ 'all other')) 

p1 <- arr %>% 
  group_by(year, disp_exp) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = year, y = n, fill=disp_exp)) +
  geom_col()

p1

p2 <- arr %>% 
  group_by(year, aor, disp_exp) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = year, y = n, fill=disp_exp)) +
  geom_col() +
  facet_wrap(~aor, scales='free_y')

p2

```

```{r meth, echo=FALSE, message=FALSE, include=TRUE}

arr %>%
  mutate(arrest_method = tolower(arrest_method)) %>% 
  group_by(arrest_method) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

```


```{r annual, echo=FALSE, message=FALSE, include=TRUE}

p1 <- arr %>% 
  group_by(fy, aor) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = fy, y=n)) +
  geom_bar(stat="identity") +
  facet_wrap(~aor)

p1

p2 <- arr %>% 
  filter(arrest_date <= "2022-09-30") %>% 
  group_by(fy, aor) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.factor(fy), y=n, color=aor, group=aor)) +
  geom_line()

ggplotly(p2)

```

```{r non-specific, echo=FALSE, message=FALSE, include=TRUE}


arr <- arr %>% 
  mutate(non_spec = case_when(str_detect(toupper(apprehension_landmark), 'NON-SPECIFIC') & !str_detect(toupper(apprehension_landmark), 'COUNTY') ~ TRUE,
                              is.na(apprehension_landmark) ~ TRUE,
                              TRUE ~ FALSE))

arr %>% 
  group_by(aor, non_spec) %>% 
  summarize(n = n()) %>% 
  mutate(freq = n / sum(n))

p1 <- arr %>% 
  group_by(aor, fy, non_spec) %>% 
  summarize(n = n()) %>% 
  mutate(freq = n / sum(n)) %>% 
  filter(non_spec == TRUE) %>% 
  ggplot(aes(x = fy, y = freq, color=aor, group=aor)) +
  geom_line() +
  gghighlight(max(freq) > .5)

p1

arr %>% filter(non_spec == TRUE) %>%
  count(apprehension_landmark) %>%
  arrange(desc(n))

```

```{r meth, echo=FALSE, message=FALSE, include=TRUE}

methods <- arr %>% 
  count(arrest_method) %>% 
  arrange(desc(n))

top_methods <- methods %>% 
  filter(n > 1000)

arr <- arr %>% 
  mutate(arrest_method_short = case_when(arrest_method %in% unlist(top_methods$arrest_method) ~ as.character(arrest_method), 
                                         TRUE ~ "All others"))

p1 <- arr %>% 
  group_by(fy, arrest_method_short) %>%
  ggplot(aes(x = fy, fill=arrest_method_short)) +
  geom_bar(stat='count')

ggplotly(p1)

p2 <- arr %>% 
  filter(!is.na(aor),
         aor != "HQ") %>% 
  group_by(aor, fy, arrest_method_short) %>%
  ggplot(aes(x = fy, fill=arrest_method_short)) +
  geom_bar(stat='count') +
  facet_wrap(~aor)

ggplotly(p2)

p3 <- arr %>% 
  filter(!is.na(aor),
         aor != "HQ") %>% 
  group_by(aor, fy, arrest_method_short) %>%
  summarize(n = n()) %>% 
  ggplot(aes(x = fy, y = n, color=arrest_method_short, group=arrest_method_short)) +
  geom_line() +
  facet_wrap(~aor)

ggplotly(p3)

```

Dates are not sorted within installments but each installment appears to be grouped by arrest date FY

```{r plot dates}

p1 <- plot(arr$id, arr$arrest_date)

p1

p2 <- arr %>% 
  group_by(arrest_date, fy) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = arrest_date, y = n, color=fy)) +
  geom_line()

ggplotly(p2)

p3 <- arr %>% 
  ggplot(aes(x=arrest_date, y = id, color = fy)) +
  geom_point()

p3

arr <- arr %>% 
  arrange(arrest_date)

plot(arr$arrest_date)
```


