---
title: "Arrest Trend Analysis"
author: "Phil Neff"
date: "12/9/2022"
output: 
  html_document: 
    code_folding: hide
---

```{r setup, include=F, warning=F, message=F}
rm(list = ls())
knitr::opts_chunk$set(warning=F, message=F, cache = T)
options(scipen = 999)

pacman::p_load('ggplot2', 'RColorBrewer', 'tidyr', 'knitr', 'ggthemes', 'lubridate', 'dplyr', 'here', 'tidyverse')

```

# Arrests

```{r cache=T}
file_in <- here::here('us', 'export', 'output', 'enforcement.csv.gz')
df <- read_delim(file_in, delim='|', col_types = cols(date = col_date(),
                                                        n_encounters = col_integer(),
                                                        n_arrests = col_integer(),
                                                        n_removals = col_integer(),
                                                        quarter = col_factor(),
                                                        fy = col_factor()))
df <- df %>% filter(aor != "HQ",
                        !is.null(aor))

arrests <- df %>% 
  dplyr::select(-c('n_encounters', 'n_removals'))

```

## Trends in arrest numbers

```{r fiscalyear_totals}
arrests <- arrests %>%
  mutate(year_month = zoo::as.yearmon(date),
         month = month(date))

p1 <- arrests %>% 
  group_by(fy) %>%
  summarize(total = n()) %>%
  ggplot(aes(fy, total, group = 1)) + 
  geom_point() +
  geom_line() +
  expand_limits(y=0) +
  labs(x = "Apprehension Year (Fiscal)",
       y = "Total Yearly Apprehension",
       title = "Total Arrests Across AOR FY 2016-2019") +
  theme_few()

p1

arrests %>% 
  group_by(month, fy) %>%
  summarize(total = n()) %>%
  mutate(Year = factor(fy)) %>%
  mutate(Month = factor(month,
                        levels = c(10:12, 1:9),
                        labels = c(month.abb[10:12], month.abb[1:9]))) %>%
  dplyr::filter(!(Year == 2019 & Month == "Sep")) %>%
  ggplot(aes(x = Month, y = total, color = Year, group = Year)) +
  geom_line() +
  geom_point() +
  scale_color_brewer(palette="Dark2") +
  theme_few() +
  theme(legend.position="bottom") +
  labs(color = "FY",
       title = "Monthly Arrests Across AOR FY 2016-2019",
       y = "Total Arrests")
 
arrests %>% 
  group_by(fy, aor) %>%
  summarize(total = n()) %>%
  ggplot(aes(as.numeric(fy), total, group = aor)) + 
  geom_line(aes(col = aor)) +
  scale_x_continuous(limits = c(2016, 2019)) +
  labs(x = "Apprehension Year (Fiscal)",
       y = "Yearly Apprehension by AOR",
       title = "Total Arrests by AOR FY 2016-2019") +
  facet_wrap(~aor) +
  theme_few() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45))

```

```{r natl_yearly_change}
natl_yearly_change <- arrests %>% 
  group_by(fy) %>%
  summarize(total = sum(n_arrests)) %>%
  pivot_wider(names_from = fy, values_from = total)

colnames(natl_yearly_change) <- c("y_2016", "y_2017", "y_2018", "y_2019")

natl_yearly_change <- natl_yearly_change %>%
  mutate(pct_change_17 = round(((y_2017-y_2016)/y_2016) * 100, 2),
         pct_change_18 = round(((y_2018-y_2017)/y_2017) * 100, 2),
         pct_change_19 = round(((y_2019-y_2018)/y_2018) * 100, 2))

natl_yearly_change$aor <- "Total"

```

```{r aor_yearly_change}

yearly_change <- arrests %>% 
  group_by(aor, fy) %>%
  summarize(total = sum(n_arrests)) %>%
  pivot_wider(names_from = fy, values_from = total) 

colnames(yearly_change) <- c("aor", "y_2016", "y_2017", "y_2018", "y_2019")

yearly_change <- yearly_change %>% rowwise() %>% 
  mutate(pct_change_17 = round(((y_2017-y_2016)/y_2016) * 100, 2),
         pct_change_18 = round(((y_2018-y_2017)/y_2017) * 100, 2),
         pct_change_19 = round(((y_2019-y_2018)/y_2018) * 100, 2))

yearly_change %>% kable(caption = "Yearly % change in arrests by AOR")

yearly_change %>% select(aor, 6:8) %>%
  pivot_longer(cols = pct_change_17:pct_change_19, names_to = "Type", values_to = "Value") %>%
  ggplot(aes(x = aor, y = Value)) + geom_bar(stat = "identity") + facet_wrap(~Type) + 
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  coord_flip() +
  labs(title = "Yearly % change in arrests by AOR") +
  theme_few()
```

```{r natl_versus_aor}

data <- rbind(natl_yearly_change, yearly_change)

aor_list <- unique(yearly_change$aor)

# current_aor <- "SEA"

pdf(here('us','analyze', 'output', 'aor_versus_natl.pdf'),width=6,height=3.25)

for (i in 1:length(aor_list)) {
  current_aor <- as.character(aor_list[i])

  p1 <- data %>% 
    filter(aor %in% c("Total", current_aor)) %>%
    dplyr::select(-starts_with("y_")) %>%
    pivot_longer(cols = starts_with("pct_change"), names_to = "Type", values_to = "Value") %>% 
    ggplot(aes(x = Type, y = Value)) +
    geom_line(aes(color=aor, group=aor)) +
    geom_point()
  
  plot(p1)
  
  data2 <- arrests %>% 
    filter(aor == current_aor) %>%
    group_by(year_month, aor) %>% 
    summarize(n_arrests = sum(n_arrests))
  
  p1a <- data2 %>% 
    ggplot(aes(x=year_month, y =n_arrests, color=aor)) +
    geom_line()
  
  plot(p1a)
  
}

dev.off()
```
