---
title: "FY12-23YTD ICE ERO descriptive analysis"
author: "UWCHR"
date: "2023-03-27"
output:
  pdf_document: default
  html_document: default
---
 

```{r setup, echo=FALSE, message=FALSE, include=TRUE}

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight)

arr <- read_delim(here('us-fy12-23', 'analyze', 'input', 'arrests.csv.gz'), delim='|',
                  col_types = cols(aor = col_character(),
                                  arrest_date = col_date(format="%m/%d/%Y"),
                                  departed_date = col_date(format="%m/%d/%Y"),
                                  apprehension_landmark = col_character(),
                                  operation = col_factor(),
                                  processing_disposition = col_factor(),
                                  citizenship_country = col_factor(),
                                  gender = col_factor(),
                                  case_closed_date = col_date(format="%m/%d/%Y"),
                                  id = col_integer(),
                                  hashid = col_character()
                                  )) 

glimpse(arr)

redacted <- c('removal_threat_level', 'apprehension_threat_level', 'alien_file_number')

arr <- arr %>% 
  dplyr::select(-redacted)

arr <- arr %>% 
  mutate(arrest_date = as_date(arrest_date, format="%m/%d/%Y"),
         year = year(arrest_date),
         month = month(arrest_date, label=TRUE, abbr=TRUE),
         year_mth = zoo::as.yearmon(arrest_date),
         fy = substr(quarter(arrest_date, fiscal_start=10, type="year.quarter"), 1,4),
         processing_disposition = tolower(processing_disposition),
         disp_exp = case_when(
           str_detect(processing_disposition, 'expedited removal') ~ TRUE,
           TRUE ~ FALSE))

rem <- read_delim(here('us-fy12-23', 'analyze', 'input', 'removals.csv.gz'), delim='|',
                  col_types = cols(aor = col_character(),
                                   arrest_date = col_date(format="%m/%d/%Y"),
                                  departed_date = col_date(format="%m/%d/%Y"),
                                  case_close_date = col_date(format="%m/%d/%Y"),
                                  removal_date = col_date(format="%m/%d/%Y"),
                                  apprehension_method_code = col_character(),
                                  processing_disposition_code = col_factor(),
                                  citizenship_country = col_factor(),
                                  gender = col_factor(),
                                  final_charge_section = col_factor(),
                                  id = col_integer(),
                                  hashid = col_character()
                                  )) 

glimpse(rem)

redacted <- c('removal_threat_level', 'alien_file_number')

rem <- rem %>% 
  dplyr::select(-redacted)

rem <- rem %>% 
  mutate(year = year(departed_date),
         month = month(departed_date, label=TRUE, abbr=TRUE),
         year_mth = zoo::as.yearmon(departed_date),
         fy = substr(quarter(departed_date, fiscal_start=10, type="year.quarter"), 1,4),
         processing_disp = coalesce(processing_disposition_code, processing_disposition),
         date = coalesce(departed_date, removal_date))

rem_processing_disp_unique <- unique(tolower(rem$processing_disp))


```

```{r rem_minus_exp}

# Filter removals for non-expedited removals
# Group counts of arrests/removals by aor/year_mth
# Difference non-expedited removals, arrests
# How does this compare to full diff analysis

```

