#
# Authors:     PN
# Maintainers: PN
# Copyright:   2024, UWCHR, GPL v2 or later
# ============================================
# ice-enforce/docs/Makefile

.PHONY: all clean

all: \
		../write/output/index.html \
		../write/output/encounters.html \
		../write/output/arrests.html \
		../write/output/removals.html \
		../write/output/landmarks.html
	cp -r ../write/output/* .

clean:
	rm output/*

# done.
